FROM python:3.12.1

# COPY
COPY /server /server
COPY wsgi.auth.py wsgi.py
COPY __init__.py __init__.py
COPY requirements.txt requirements.txt

# SETUP PYTHON PKG
RUN pip install -r requirements.txt

# ENVs
ENV DEBUG=false
ENV SQLALCHEMY_TRACK_MODIFICATIONS=false
ENV JWT_ACCESS_TOKEN_EXPIRES_MINUTES=15
ENV JWT_REFRESH_TOKEN_EXPIRES_MINUTES=43200
ENV REDIS_PORT=6379

# PORT EXPOSING
EXPOSE 5001

# START AUTH SERVICE
CMD if [ "$DEBUG" = "true" ] ; \
    then \
        python wsgi.py ; \
    else \
        gunicorn -b 0.0.0.0:5001 wsgi:app ; \
    fi
# CMD ["python", "wsgi.py"]
# CMD ["gunicorn", "-b", "0.0.0.0:5001", "wsgi:app"]
