version: "3"
name: "weeklychef-backend-prod"

services:
  database-recipe-service:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dbrootpassword
      MYSQL_DATABASE: weeklychef
      MYSQL_USER: serviceuser
      MYSQL_PASSWORD: devpassword
    volumes:
      - db-recipe-data:/home/enricogoerlitz/weeklychef-recipe/mysql

  database-auth-service:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dbrootpassword
      MYSQL_DATABASE: weeklychef
      MYSQL_USER: serviceuser
      MYSQL_PASSWORD: devpassword
    volumes:
      - db-auth-data:/home/enricogoerlitz/weeklychef-auth/mysql

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  auth-service:
    image: enricogoerlitz/weeklychef-auth-service:latest
    ports:
      - "5001:5001"
    restart: always
    environment:
      DEBUG: false
      SQLALCHEMY_DATABASE_URI: "mysql://serviceuser:devpassword@database-auth-service:3306/weeklychef"
      SQLALCHEMY_TRACK_MODIFICATIONS: false
      JWT_SECRET_KEY: "f1ae9b76935d89426cec6993698e865c1a12574ac9deb393dcdbc8f21eb76998"
      JWT_ACCESS_TOKEN_EXPIRES_MINUTES: 43200
      JWT_REFRESH_TOKEN_EXPIRES_MINUTES: 86400
      SWAGGER_API_VERSION: "1.0"
      SWAGGER_API_TITLE: "WeeklyChef API v1.0"
      SWAGGER_API_DESCRIPTION: "WeeklyChef Authentication Service REST API"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - database-auth-service
      - redis

  recipe-service:
    image: enricogoerlitz/weeklychef-recipe-service:latest
    ports:
      - "5002:5002"
    restart: always
    environment:
      DEBUG: false
      SQLALCHEMY_DATABASE_URI: "mysql://serviceuser:devpassword@database-recipe-service:3306/weeklychef"
      SQLALCHEMY_TRACK_MODIFICATIONS: false
      JWT_SECRET_KEY: "f1ae9b76935d89426cec6993698e865c1a12574ac9deb393dcdbc8f21eb76998"
      JWT_ACCESS_TOKEN_EXPIRES_MINUTES: 43200
      JWT_REFRESH_TOKEN_EXPIRES_MINUTES: 86400
      SWAGGER_API_VERSION: "1.0"
      SWAGGER_API_TITLE: "WeeklyChef API v1.0"
      SWAGGER_API_DESCRIPTION: "WeeklyChef Recipe Service REST API"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - recipe-images:/home/enricogoerlitz/weeklychef-recipe/images
    depends_on:
      - auth-service

volumes:
  db-recipe-data:
  db-auth-data:
  recipe-images:
