version: "3"
name: "weeklychef-backend"

services:
  recipe-service:
    build:
      - # TODO: IMAGE
    ports:
      - "5002:5002"
    restart: always
    environment:
      DEBUG: false
      SQLALCHEMY_DATABASE_URI: # TODO: CHANGE => "mysql://serviceuser:devpassword@database-recipe-service:3306/weeklychef"
      SQLALCHEMY_TRACK_MODIFICATIONS: false
      JWT_SECRET_KEY: # TODO: CHANGE => "f1ae9b76935d89426cec6993698e865c1a12574ac9deb393dcdbc8f21eb76998"
      SWAGGER_API_VERSION: "1.0"
      SWAGGER_API_TITLE: "WeeklyChef API v1.0"
      SWAGGER_API_DESCRIPTION: "WeeklyChef Recipe Service REST API"
      REDIS_HOST: # TODO: CHANGE => redis
      REDIS_PORT: # TODO: CHANGE => 6379
    volumes:
      - recipe-images:/Users/enricogoerlitz/weeklychef/images  # GoogleDrive in future!

volumes:
  recipe-images:
# TODO: Token ex=15min / Refresh Token ex=30Tage!