# in /etc/netplan/{.yaml}
# sudo netplan apply
# sudo reboot apply

network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s1:
      addresses:
        - 192.168.64.101/24
      nameservers:
        addresses: [1.1.1.1, 1.0.0.1]
      routes:
        - to: default
          via: 192.168.0.1
